[package]
name = "cowonverter"
version = "2.0"
authors = ["Bensatankki <axu.hartikainen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
structopt = "0.3.13"
